
services:
  app:
    container_name: Task_manager
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
